import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { fetchRandomCocktail } from '../apiUtils/Cocktails';
import SingleCocktail from '../components/cocktails/SingleCocktail';
import MainLayout from '../layouts/MainLayout';
import styles from '../styles/Home.module.css';
const Home: NextPage = ({ randomCocktail }: any) => {
	return (
		<MainLayout>
			<Head>
				<title>{randomCocktail?.strDrink}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SingleCocktail cocktail={randomCocktail} />
		</MainLayout>
	);
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx: any) => {
	const randomCocktail = await fetchRandomCocktail();
	return {
		props: {
			randomCocktail,
		},
	};
};
